jwt:
  access_token_secret: 9jF8Vbr0wdow/Ixz0eerLuityvlJGYANPu5FWvKTV/w=--pF9IDW86Bty7YagA/kM+qQ==
  refresh_token_secret: hiAQvNO4RruHwtr75q8RMdieMTpgOiOi1dVNVR5ivWY=--0AtZy1Yvr67oWUIQQOvCJw==

swagger:
  username: m+oQ+NP/cPm58ld2fHSb9HcdpKB6o0+4T0kWT8udBRU=--t3DkpyVKn0VM+db0mSlHCw==
  password: Dpum+aCXdLLVX5b95rBteUcBsTNwhQg1TStHE3kYuGo=--JdGjHB3YISlL6rjvCisYqQ==

common:
  app_name: D/D9MIGTPrao+QNKxEo0Hw==--lqKONnVH7neGUKC7EKPd7Q==

database:
  name: /pxXS1TmgVz6PQd+BT57OXiRdHegaBqnDEaF3109IgA=--Yk1zCDinbyOR0892QgYlsQ==
  host: 5/taZXCYjXaM86j39k+HRw==--Myyf/pbz/rL7+gzBiaqqsg==
  username: kWiKqQvfx6MMJyOLSzL7wA==--7JPyn5aTjUNgaDjw/eV/gA==
  password: baLm6ZRUnBFXJcRlpaxBLg==--oyRjig36oGOsbE97Q12dFQ==
  port: eGJ+9QTOmUYj9Ua6ZJBTTQ==--A5jcfeq7F9sVsSzbl1FLgg==