jwt:
  access_token_secret: rHm5hVXrugMVHFYRw6eOvSwDYoBqRL1jDCduIKsfUA8=--zgi0C+nNRUCrc2fX+WCDaw==
  refresh_token_secret: IzbaRTlAejLy8d2wCm9PvQQxcXjUGVuZyLcSuYe12hc=--mrPT2ANN9/gNYokMIVEArg==

swagger:
  username: LJhTDeh6b0I4Egi9iXYHLccwCdmu1qedzH0mlDfuSVo=--w/ifXEDmQpb6ZZ5scab0nQ==
  password: IILBQ5wftdVYUv6ZGLJ40NS9/S9DypJYqk7FlUc/Yp4=--vTi201y+2Yp/Pr4VRr90GQ==

common:
  app_name: ATWf4U1qKSkf8b57y1uBpA==--yk2MhjAF6ldXh9J9RNU6TA==

database:
  name: sj68rrU++fmQs1uZoOpRETgSVigeyKSZNTB58FWGxZk=--NVi798lcnc8MNcU4dtNfHQ==
  host: tfQGfwrBP83M9g0t9IeAtg==--PGCN2aY2/ASPKcw/gyO16A==
  username: FWj8O+/9+dKapZNljy+TAg==--9V3AOZo+cILeSUgp4pE7xQ==
  password: iRq+kNZ5T5Tby/Ms6Xk7vg==--rckYfwQmiCN4Fy9cuPzqiw==
  port: KsWXZZMR9mIGp1e31uw3GA==--wg1XbO8RQjwRIJ5daEe5oQ==